version: '3.3'

services:
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: hue
            MYSQL_USER: hue
            MYSQL_PASSWORD: hue
        expose:
            - '3306'
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql
    hive:
        image: dvoros/hive
        ports:
            - '10000:10000'
        tty: true
        volumes:
            - $PROJECT_HOME/hive/data:/tmp/data
    hue:
        image: gethue/hue
        expose:
            - '8888'
        ports:
            - '8888:8888'
        volumes:
            - $PROJECT_HOME/hue/conf/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini:ro
            - $PROJECT_HOME/hive/conf:/etc/hive/conf:ro
        depends_on:
            - mysql
            - hive
        command: >
            /bin/bash -c "
                sleep 30;
                ./startup.sh;
            "

volumes:
    mysql_data: {}
