version: '3.3'

services:
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: hue
            MYSQL_USER: hue
            MYSQL_PASSWORD: hue
        ports:
            - '3306:3306'
        volumes:
            - $PROJECT_HOME/mysql/data:/var/lib/mysql
            - $PROJECT_HOME/mysql/custom:/etc/mysql/conf.d
    hive:
        image: psyoblade/hive
        ports:
            - '8088:8088'
            - '9083:9083'
            - '10000:10000'
            - '50070:50070'
        tty: true
        environment:
            - LANG=ko_KR.UTF8
        volumes:
            - $PROJECT_HOME/hive/data:/tmp/data
    hue:
        image: gethue/hue
        ports:
            - '8888:8888'
        volumes:
            - $PROJECT_HOME/hue/conf/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini:ro
            - $PROJECT_HOME/hive/conf:/etc/hive/conf:ro
        depends_on:
            - mysql
            - hive
        command: >
            /bin/bash -c "
                sleep 10;
                ./startup.sh;
            "
